# Generated by Django 3.2.5 on 2021-07-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('staff_id', models.CharField(max_length=50)),
                ('phone', models.CharField(default='+255716228159', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('license', models.CharField(max_length=50, unique=True)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], default='Auto', max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('seats', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('operability', models.CharField(choices=[('Operable', 'Operable'), ('Inoperable', 'Inoperable')], default='Operable', max_length=50)),
                ('maintenance_record', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=50)),
                ('tank', models.CharField(default=80, max_length=50)),
                ('last_refill', models.CharField(max_length=50)),
                ('mileage', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Refilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now=True)),
                ('towards', models.CharField(max_length=60)),
                ('fuel', models.CharField(max_length=60)),
                ('liters', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=60)),
                ('driver', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_seat', models.CharField(max_length=50)),
                ('horn', models.CharField(max_length=50)),
                ('steering', models.CharField(max_length=50)),
                ('brakes', models.CharField(max_length=50)),
                ('indicators', models.CharField(max_length=50)),
                ('speedometer', models.CharField(max_length=50)),
                ('wipers', models.CharField(max_length=50)),
                ('body_interior', models.CharField(max_length=50)),
                ('extinguisher', models.CharField(max_length=50)),
                ('first_aid', models.CharField(max_length=50)),
                ('floor_traps', models.CharField(max_length=50)),
                ('emergency', models.CharField(max_length=50)),
                ('passenger_door', models.CharField(max_length=50)),
                ('mirrors', models.CharField(max_length=50)),
                ('body_exterior', models.CharField(max_length=50)),
                ('discs', models.CharField(max_length=50)),
                ('inflation', models.CharField(max_length=50)),
                ('spare_wheel', models.CharField(max_length=50)),
                ('fixing', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('exhaust', models.CharField(max_length=50)),
                ('reflectors', models.CharField(max_length=50)),
                ('lice_plate_condition', models.CharField(max_length=50)),
                ('defect', models.TextField(blank=True, max_length=255)),
                ('action', models.TextField(blank=True, max_length=255)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.vehicle')),
            ],
        ),
    ]
