# Generated by Django 3.2.4 on 2021-06-08 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_request_trip_time'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='staff_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staff.request'),
        ),
    ]
