# Generated by Django 3.2.4 on 2021-06-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_assigned_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=50)),
                ('maintenance_record', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'Ontrip'), ('Garage', 'Garage')], default='Available', max_length=50)),
                ('last_refill', models.CharField(max_length=50)),
            ],
        ),
    ]
