# Generated by Django 3.2.5 on 2021-08-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_maintainance_majormaintainance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='license',
            field=models.CharField(max_length=50),
        ),
    ]
