# Generated by Django 3.2.5 on 2021-08-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_inspection_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(default='david', max_length=50),
        ),
    ]
