# Generated by Django 3.2.4 on 2021-06-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='millaege',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
