# Generated by Django 3.2.4 on 2021-06-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_vehicle_millaege'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tank',
            field=models.CharField(default=80, max_length=50),
        ),
    ]
