# Generated by Django 3.2.5 on 2021-08-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driver_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='staff_id',
            field=models.CharField(blank=True, default='Not Assigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.CharField(blank=True, default='Not Assigned', max_length=50),
        ),
    ]
