# Generated by Django 3.2.4 on 2021-06-08 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_vehicle_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_seat_belt', models.BooleanField(default=True)),
                ('horn', models.BooleanField(default=True)),
                ('steering', models.BooleanField(default=True)),
                ('brakes', models.BooleanField(default=True)),
                ('indicators', models.BooleanField(default=True)),
                ('speedometer', models.BooleanField(default=True)),
                ('wipers', models.BooleanField(default=True)),
                ('body_interior', models.BooleanField(default=True)),
                ('extinguisher', models.BooleanField(default=True)),
                ('first_aid', models.BooleanField(default=True)),
                ('floor_traps', models.BooleanField(default=True)),
                ('hammers', models.BooleanField(default=True)),
                ('emergency', models.BooleanField(default=True)),
                ('passenger_door', models.BooleanField(default=True)),
                ('mirrors', models.BooleanField(default=True)),
                ('body_exterior', models.BooleanField(default=True)),
                ('discs', models.BooleanField(default=True)),
                ('glass', models.BooleanField(default=True)),
                ('spare_wheel', models.BooleanField(default=True)),
                ('tyres', models.BooleanField(default=True)),
                ('engine_oil', models.BooleanField(default=True)),
                ('engine_water', models.BooleanField(default=True)),
                ('fuel', models.BooleanField(default=True)),
                ('battery', models.BooleanField(default=True)),
                ('exhaust', models.BooleanField(default=True)),
                ('reflectors', models.BooleanField(default=True)),
                ('lice_plate_condition', models.BooleanField(default=True)),
                ('defect', models.TextField(max_length=255)),
                ('action', models.TextField(max_length=255)),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.vehicle')),
            ],
        ),
    ]
