# Generated by Django 3.2.5 on 2021-08-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20210802_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='body_exterior',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='body_interior',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='brakes',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='discs',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='driver_seat',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='exhaust',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='extinguisher',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='first_aid',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='fixing',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='floor_traps',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='horn',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inflation',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='mirrors',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='passenger_door',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='reflectors',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='spare_wheel',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='speedometer',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='steering',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='wipers',
        ),
        migrations.AddField(
            model_name='inspection',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='driver',
            field=models.CharField(default='User', max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='odometer',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
