# Generated by Django 3.2.4 on 2021-06-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='action',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='defect',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
