# Generated by Django 3.2.4 on 2021-06-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20210609_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='millaege',
            new_name='mileage',
        ),
    ]
