# Generated by Django 3.2.5 on 2021-08-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20210804_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='action',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='lice_plate_condition',
        ),
    ]
