# Generated by Django 3.2.5 on 2021-08-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_auto_20210804_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainance',
            name='driver',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maintainance',
            name='vehicle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='majormaintainance',
            name='vehicle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='refilling',
            name='driver',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='refilling',
            name='vehicle',
            field=models.CharField(max_length=50),
        ),
    ]
