# Generated by Django 3.2.4 on 2021-06-16 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_remove_request_edit'),
        ('driver', '0008_rename_millaege_vehicle_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='staff_id',
            field=models.ForeignKey(blank=True, default='Null', on_delete=django.db.models.deletion.SET_DEFAULT, to='staff.request'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='license_plate',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.SET_DEFAULT, to='driver.vehicle'),
        ),
    ]
