# Generated by Django 3.2.5 on 2021-08-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210619_1118'),
        ('driver', '0009_auto_20210805_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomRefill',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
            ],
        ),
    ]
