# Generated by Django 3.2.4 on 2021-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_auto_20210616_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='staff_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='license_plate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
