# Generated by Django 3.2.5 on 2021-08-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_randomrefill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
