# Generated by Django 3.2.4 on 2021-06-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_auto_20210621_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='driver_seat_belt',
            new_name='driver_seat',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='engine_oil',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='engine_water',
            new_name='fixing',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='fuel',
            new_name='inflation',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='glass',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='hammers',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='tyres',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='license_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.vehicle'),
        ),
    ]
