# Generated by Django 3.2.5 on 2021-08-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20210805_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintainance',
            old_name='type',
            new_name='mtype',
        ),
    ]
