# Generated by Django 3.2.5 on 2021-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_maintainance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainance',
            name='mtype',
            field=models.CharField(max_length=50),
        ),
    ]
