# Generated by Django 3.2.5 on 2021-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_alter_maintainance_mtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainance',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
