# Generated by Django 3.2.5 on 2021-08-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0019_alter_locations_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='time',
            new_name='timesent',
        ),
    ]
