# Generated by Django 3.2.5 on 2021-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0020_rename_time_locations_timesent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='timesent',
        ),
        migrations.AddField(
            model_name='locations',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
