# Generated by Django 3.2.5 on 2021-08-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0021_auto_20210810_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintainance',
        ),
        migrations.DeleteModel(
            name='MajorMaintainance',
        ),
    ]
