# Generated by Django 3.2.5 on 2021-08-14 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0023_auto_20210814_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refilling',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.AddField(
            model_name='refilling',
            name='hr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='humanresource', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refilling',
            name='received_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refilling',
            name='sent_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
