# Generated by Django 3.2.5 on 2021-08-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transportofficer'),
        ('driver', '0024_auto_20210815_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refilling',
            name='received_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transport', to='main.transportofficer'),
        ),
    ]
