# Generated by Django 3.2.5 on 2021-08-14 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0025_alter_refilling_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refilling',
            name='received_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transport', to=settings.AUTH_USER_MODEL),
        ),
    ]
