# Generated by Django 3.2.5 on 2021-08-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0026_alter_refilling_received_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refilling',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='refilling',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='refilling',
            name='sent_by',
        ),
    ]
