# Generated by Django 3.2.5 on 2021-08-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0027_auto_20210815_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_id',
        ),
    ]
