# Generated by Django 3.2.5 on 2021-07-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('department', models.CharField(default='CCT', max_length=50)),
                ('destination', models.CharField(default='POSTA', max_length=50)),
                ('contact', models.CharField(default='0712345678', max_length=50)),
                ('purpose', models.TextField()),
                ('trip_date', models.CharField(max_length=50)),
                ('time', models.CharField(default='12:00', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('driver', models.CharField(blank=True, default='Not Assigned', max_length=50)),
            ],
        ),
    ]
