# Generated by Django 3.2.4 on 2021-06-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('trip_details', models.TextField()),
                ('trip_time', models.DateField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
