# Generated by Django 3.2.4 on 2021-06-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='trip_time',
            field=models.DateTimeField(),
        ),
    ]
