# Generated by Django 3.2.5 on 2021-08-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
