# Generated by Django 3.2.5 on 2021-08-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_by',
            field=models.CharField(blank=True, default='Not Approved', max_length=50),
        ),
    ]
