# Generated by Django 3.2.4 on 2021-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_request_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='edit',
            field=models.CharField(default='Edit', max_length=5),
        ),
    ]
