# Generated by Django 3.2.4 on 2021-06-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_request_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='edit',
        ),
    ]
