# Generated by Django 3.2.4 on 2021-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='staff_id',
            field=models.TextField(default='NIT/Staff/1', max_length=10, unique=True),
        ),
    ]
