# Generated by Django 3.2.4 on 2021-06-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Transport'), (2, 'Driver'), (3, 'hr'), (4, 'Staff'), (5, 'Workshop'), (6, 'Gpsa')], default=4),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
