# Generated by Django 3.2.4 on 2021-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_users_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='staff_id',
            field=models.TextField(default='NIT/Staff/1', max_length=50, unique=True),
        ),
    ]
