# Generated by Django 3.2.4 on 2021-06-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=50)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('assigned', models.CharField(max_length=50)),
            ],
        ),
    ]
