# Generated by Django 3.2.4 on 2021-06-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_rename_millaege_vehicle_mileage'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestatus',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.vehicle'),
        ),
    ]
