# Generated by Django 3.2.4 on 2021-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vehiclestatus_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestatus',
            name='vehicle',
            field=models.CharField(max_length=50),
        ),
    ]
