# Generated by Django 3.2.5 on 2021-08-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0026_alter_refilling_received_by'),
        ('main', '0002_transportofficer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportOfficer',
        ),
    ]
