# Generated by Django 3.2.5 on 2021-08-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20210814_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='majormaintainance',
            name='user',
        ),
    ]
